function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "my_wmm_test"};
	this.sidHashMap["my_wmm_test"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "my_wmm_test:5"};
	this.sidHashMap["my_wmm_test:5"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<S2>"] = {sid: "my_wmm_test:5:9"};
	this.sidHashMap["my_wmm_test:5:9"] = {rtwname: "<S2>"};
	this.rtwnameHashMap["<Root>/Constant"] = {sid: "my_wmm_test:8"};
	this.sidHashMap["my_wmm_test:8"] = {rtwname: "<Root>/Constant"};
	this.rtwnameHashMap["<Root>/Constant1"] = {sid: "my_wmm_test:9"};
	this.sidHashMap["my_wmm_test:9"] = {rtwname: "<Root>/Constant1"};
	this.rtwnameHashMap["<Root>/Constant2"] = {sid: "my_wmm_test:10"};
	this.sidHashMap["my_wmm_test:10"] = {rtwname: "<Root>/Constant2"};
	this.rtwnameHashMap["<Root>/Constant3"] = {sid: "my_wmm_test:11"};
	this.sidHashMap["my_wmm_test:11"] = {rtwname: "<Root>/Constant3"};
	this.rtwnameHashMap["<Root>/To Workspace"] = {sid: "my_wmm_test:12"};
	this.sidHashMap["my_wmm_test:12"] = {rtwname: "<Root>/To Workspace"};
	this.rtwnameHashMap["<Root>/To Workspace1"] = {sid: "my_wmm_test:13"};
	this.sidHashMap["my_wmm_test:13"] = {rtwname: "<Root>/To Workspace1"};
	this.rtwnameHashMap["<Root>/magField_custom_lib"] = {sid: "my_wmm_test:5"};
	this.sidHashMap["my_wmm_test:5"] = {rtwname: "<Root>/magField_custom_lib"};
	this.rtwnameHashMap["<S1>/alt_m"] = {sid: "my_wmm_test:5:2"};
	this.sidHashMap["my_wmm_test:5:2"] = {rtwname: "<S1>/alt_m"};
	this.rtwnameHashMap["<S1>/lat_deg"] = {sid: "my_wmm_test:5:4"};
	this.sidHashMap["my_wmm_test:5:4"] = {rtwname: "<S1>/lat_deg"};
	this.rtwnameHashMap["<S1>/lon_deg"] = {sid: "my_wmm_test:5:5"};
	this.sidHashMap["my_wmm_test:5:5"] = {rtwname: "<S1>/lon_deg"};
	this.rtwnameHashMap["<S1>/decimal_year"] = {sid: "my_wmm_test:5:6"};
	this.sidHashMap["my_wmm_test:5:6"] = {rtwname: "<S1>/decimal_year"};
	this.rtwnameHashMap["<S1>/MATLAB Function"] = {sid: "my_wmm_test:5:9"};
	this.sidHashMap["my_wmm_test:5:9"] = {rtwname: "<S1>/MATLAB Function"};
	this.rtwnameHashMap["<S1>/B_NED_nT"] = {sid: "my_wmm_test:5:3"};
	this.sidHashMap["my_wmm_test:5:3"] = {rtwname: "<S1>/B_NED_nT"};
	this.rtwnameHashMap["<S1>/FLAG"] = {sid: "my_wmm_test:5:10"};
	this.sidHashMap["my_wmm_test:5:10"] = {rtwname: "<S1>/FLAG"};
	this.rtwnameHashMap["<S2>:1"] = {sid: "my_wmm_test:5:9:1"};
	this.sidHashMap["my_wmm_test:5:9:1"] = {rtwname: "<S2>:1"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
