% Unit test file for SOAR library
%
% problem parameters defined in init_SOAR, all parameters in soar_params.
% 
% this file tests the same scenario as the matlab demo in
% test/soar_matlab_demo for consistency. The plots generated should match
% the ones generated by both the CVX and ECOS tests in that folder.
%
% T. Reynolds -- RAIN Lab

N     = 10; % number of discretization nodes
w_max = 0.1;
T_max = 2.3e-3;
Jw    = diag([2.9382e-5,2.9382e-5,2.9382e-5]);

% initial conditions
n   = [1;1;1]./norm([1;1;1]);
q0  = [ cosd(60/2); sind(60/2).*n ];
w0  = [ 0.0; 0.0; 0.0 ];
hw0 = Jw * 0.10471975511966 * [ 1000; 1000; 1000 ]; % rad/s

% final conditions
qd  = [ cosd(0/2); sind(0/2).*n ];
qf  = [ 1.0; 0.0; 0.0; 0.0 ]; %quatmultiply(qd',q0')';%
wf  = [ 0.0; 0.0; 0.0 ];

% inertial sun vector
sI  = [ 1.0; 0.0; 0.0 ];

% Load sim and set run time
run_time    = 600;
mdl         = 'soar_unit_test';
load_system(mdl);
set_param(mdl,'StopTime', num2str(run_time));

% run test case
sim(mdl);

%% analyze results
num_sims = size(x_star,1);
xopt = x_star(end,:);
uopt = u_star(end,:);
sopt = s_star(end,:);
exitcode = exitcode(end,:);

if (exitcode(end) ~=0 )
    msg = sprintf('Did not converge with exitcode %d\n', exitcode(end));
else
    msg = sprintf('Converged in %d iterations.\n', exitcode(end-1));
end
fprintf('========================\n')
fprintf('SOAR UNIT TEST RESULTS:\n')
fprintf('========================\n')
fprintf(msg)


% Integrate through ODE
T       = linspace(0,sopt,100);
xopt    = reshape(full(xopt),10,N);
uopt    = reshape(full(uopt),3,N);
ut      = linspace(0,sopt,N);
P.method  = 'linear';
P.inertia = soarParams.inertia;

% integrate solution through nonlinear dynamics
X = rk4(@(t,y)Q_ode_p(P,t,y,uopt,ut),T,full(xopt(1:10)));

% Plot
close all
figure(1)
subplot(3,1,1), hold on, grid on
plot(T,X(:,1:4),'LineWidth',1)
plot(ut,xopt(1:4,:),'k*','MarkerSize',3)
set(gca,'Ylim',[-1 1])
xlabel('Time [s]','FontSize',16)
title('Attitude Quaternion','FontSize',18)
subplot(3,1,2), hold on, grid on
plot(T,P.inertia\X(:,5:7)','LineWidth',1)
plot(ut,P.inertia\xopt(5:7,:),'k*','MarkerSize',3)
plot([0 sopt],[w_max w_max],'r--','LineWidth',1)
plot([0 sopt],[-w_max -w_max],'r--','LineWidth',1)
xlabel('Time [s]','FontSize',16)
title('Angular Velocity','FontSize',18)
subplot(3,1,3), hold on, grid on
plot(T,X(:,8:10),'LineWidth',1)
plot(ut,xopt(8:10,:),'k*','MarkerSize',3)
xlabel('Time [s]','FontSize',16)
title('Wheel Momentum','FontSize',18)

figure(2), hold on, grid on
plot(ut,uopt,'LineWidth',1)
plot([0 sopt],[T_max T_max],'r--','LineWidth',1)
plot([0 sopt],[-T_max -T_max],'r--','LineWidth',1)
xlabel('Time [s]','FontSize',16)
title('Control Signal','FontSize',18)